{
 "title": "Jenkins",
 "description": "Jenkins dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_builds_count" }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_unstable_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "vm_uptime_milliseconds" }
   ]
  },
  {
   "title": "Disk usage for each job in bytes",
   "type": "graph",
   "description": "Amount of disk usage (bytes) for each job in Jenkins",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(default_jenkins_job_usage_bytes) by (jobName)",
     "legendFormat": "{{jobName}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Jenkins build success",
   "type": "graph",
   "description": "Successful build count",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(default_jenkins_builds_success_build_count[1m]))"
    }
   ]
  },
  {
   "title": "Jenkins build failed",
   "type": "graph",
   "description": "Failed build count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(default_jenkins_builds_failed_build_count[1m]))"
    }
   ]
  },
  {
   "title": "Job waiting duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.waiting.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_waiting_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Task execution duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.task.execution.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_task_execution_duration",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Job total duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.total.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_total_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Health check duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.health-check.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_health_check_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Project count history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.project.count.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_project_count_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Node offline history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.node.offline.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_offline_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Node count history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.node.count.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_count_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Node online history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.node.offline.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_online_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins queue size history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.queue.size.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_size_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Project enabled count history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.project.enabled.count.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_project_enabled_count_history",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Job building duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.building.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_building_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins node windows slave builds history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.node.windows_slave.builds, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_node_windows_slave_builds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Jenkins queue pending history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.queue.pending.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_online_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins task queuing duration history",
   "type": "graph",
   "description": " Generated from Dropwizard metric import (metric=jenkins.task.queuing.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_task_queuing_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins queue buildable history",
   "type": "graph",
   "description": " Generated from Dropwizard metric import (metric=jenkins.queue.buildable.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_queue_buildable_history",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Jenkins job blocked history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.blocked.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_blocked_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins job buildable duration history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.buildable.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_buildable_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins queue stuck history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.queue.stuck.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_stuck_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins queuing duration history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.queuing.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins task buildable duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.task.buildable.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_task_buildable_duration",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Jenkins task waiting duration",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.task.waiting.duration, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_task_waiting_duration", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins project disabled count history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.project.disabled.count.history, type=jenkins.metrics.util.AutoSamplingHistogram)\n# TYPE jenkins_project_disabled_count_history summary",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_history",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Jenkins executor count history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.executor.count.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_executor_count_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins execution time history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.job.execution.time, type=com.codahale.metrics.Timer)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_execution_time", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins executor in use history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.executor.in-use.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_executor_in_use_history",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Jenkins executor free history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.executor.free.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_executor_free_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Jenkins executor free history",
   "type": "graph",
   "description": "Generated from Dropwizard metric import (metric=jenkins.executor.free.history, type=jenkins.metrics.util.AutoSamplingHistogram)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_executor_free_history", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration)/sum(jenkins_job_building_duration_count))"
    }
   ]
  }
 ]
}